usemem.c: Add missing opt_repeat
Fix the following compiler error:
----------------------------------------
usemem.c:711:17: error: too many arguments to function ‘do_rw_once’
     rw_bytes += do_rw_once(ptrs[i], lens[i], &rand_data, 1, &rep, opt_repeat);
                 ^~~~~~~~~~
...
usemem.c:763:16: error: too many arguments to function ‘do_rw_once’
   unit_bytes = do_rw_once(buffer, opt_bytes, &rand_data, 1, NULL, 0);
                ^~~~~~~~~~
usemem.c:463:22: note: declared here
 static unsigned long do_rw_once(unsigned long *p, unsigned long bytes,
                      ^~~~~~~~~~
----------------------------------------

Fixes: 4b12da9("usemem: rename reps to opt_repeat")
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Xiao Yang <xiaox.yang@intel.com>

Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>